name: Build & publish with gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
    - '*' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant permission
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  
  apk-gen:
    name: Create Android APK file
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build APK with gradle
      run: ./gradlew assembleDebug
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
          
  publish:
    name: Puplish apk
    needs: apk-gen
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Download APK from build
      uses: actions/download-artifact@v3
      with:
        name: apk
    - name: Archive files
      run: |
          sudo apt-get install zip
          cd apk
          zip -r *
          cd..

    - name: Upload to Google drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.credentials }}
        filename: "soundofhell.zip"
        folderId: ${{ secrets.folderId }}
        overwrite: "true"
      
    
    
  
      
    
          
