name: Automatic code review
on: 
  pull_request
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - uses: actions/checkout@v3
    - name: Check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        fail_on_error: true
        checkstyle_config: 'codestyle/checkstyle.xml'
        checkstyle_version: '8.42'
