name: Build & publish docker image

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3    
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
      - name: Build & push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: newronin/devops-practice:latest
