name: Build & publish docker image

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
      - name: Build & push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: newronin/devops-practice:latest
          
  local-test:
    name: Local machine run
    runs-on: self-hosted
    needs: docker
    
    steps:
      - name: Pull image
        run: docker pull newronin/devops-practice:latest
      - name: Run docker container
        run: docker run --name app -p 80:8080 -d newronin/devops-practice:latest
    
    
  
